const menuItems = {
  rest_001: [
    {
      id: "item_001_001",
      name: "Chicken Tikka Masala",
      price: 16.99,
      category: "Main Course",
      description: "Tender chicken in creamy tomato sauce",
      image: "https://example.com/tikka-masala.jpg",
      spiceLevel: "Medium",
      vegetarian: false,
    },
    {
      id: "item_001_002",
      name: "Paneer Butter Masala",
      price: 14.99,
      category: "Main Course",
      description: "Cottage cheese in rich butter sauce",
      image: "https://example.com/paneer-butter.jpg",
      spiceLevel: "Mild",
      vegetarian: true,
    },
    {
      id: "item_001_003",
      name: "Biryani Chicken",
      price: 18.99,
      category: "Rice",
      description: "Fragrant basmati rice with spiced chicken",
      image: "https://example.com/biryani.jpg",
      spiceLevel: "Medium",
      vegetarian: false,
    },
    {
      id: "item_001_004",
      name: "Naan Bread",
      price: 3.99,
      category: "Bread",
      description: "Fresh baked Indian flatbread",
      image: "https://example.com/naan.jpg",
      spiceLevel: "None",
      vegetarian: true,
    },
    {
      id: "item_001_005",
      name: "Samosa",
      price: 5.99,
      category: "Appetizer",
      description: "Crispy pastry with spiced potatoes",
      image: "https://example.com/samosa.jpg",
      spiceLevel: "Mild",
      vegetarian: true,
    },
    {
      id: "item_001_006",
      name: "Dal Makhani",
      price: 12.99,
      category: "Main Course",
      description: "Creamy black lentils",
      image: "https://example.com/dal-makhani.jpg",
      spiceLevel: "Mild",
      vegetarian: true,
    },
    {
      id: "item_001_007",
      name: "Tandoori Chicken",
      price: 19.99,
      category: "Main Course",
      description: "Clay oven roasted chicken",
      image: "https://example.com/tandoori.jpg",
      spiceLevel: "Medium",
      vegetarian: false,
    },
    {
      id: "item_001_008",
      name: "Mango Lassi",
      price: 4.99,
      category: "Beverage",
      description: "Sweet yogurt drink with mango",
      image: "https://example.com/lassi.jpg",
      spiceLevel: "None",
      vegetarian: true,
    },
    {
      id: "item_001_009",
      name: "Palak Paneer",
      price: 14.99,
      category: "Main Course",
      description: "Cottage cheese in spinach gravy",
      image: "https://example.com/palak-paneer.jpg",
      spiceLevel: "Mild",
      vegetarian: true,
    },
    {
      id: "item_001_010",
      name: "Chicken Curry",
      price: 15.99,
      category: "Main Course",
      description: "Traditional Indian chicken curry",
      image: "https://example.com/chicken-curry.jpg",
      spiceLevel: "Hot",
      vegetarian: false,
    },
    {
      id: "item_001_011",
      name: "Aloo Gobi",
      price: 11.99,
      category: "Main Course",
      description: "Cauliflower and potato curry",
      image: "https://example.com/aloo-gobi.jpg",
      spiceLevel: "Medium",
      vegetarian: true,
    },
    {
      id: "item_001_012",
      name: "Garlic Naan",
      price: 4.99,
      category: "Bread",
      description: "Naan bread with fresh garlic",
      image: "https://example.com/garlic-naan.jpg",
      spiceLevel: "None",
      vegetarian: true,
    },
    {
      id: "item_001_013",
      name: "Chicken Vindaloo",
      price: 17.99,
      category: "Main Course",
      description: "Spicy Goan chicken curry",
      image: "https://example.com/vindaloo.jpg",
      spiceLevel: "Very Hot",
      vegetarian: false,
    },
    {
      id: "item_001_014",
      name: "Jeera Rice",
      price: 6.99,
      category: "Rice",
      description: "Cumin flavored basmati rice",
      image: "https://example.com/jeera-rice.jpg",
      spiceLevel: "None",
      vegetarian: true,
    },
    {
      id: "item_001_015",
      name: "Papadum",
      price: 2.99,
      category: "Appetizer",
      description: "Crispy lentil wafers",
      image: "https://example.com/papadum.jpg",
      spiceLevel: "None",
      vegetarian: true,
    },
    {
      id: "item_001_016",
      name: "Butter Chicken",
      price: 16.99,
      category: "Main Course",
      description: "Creamy tomato chicken curry",
      image: "https://example.com/butter-chicken.jpg",
      spiceLevel: "Mild",
      vegetarian: false,
    },
    {
      id: "item_001_017",
      name: "Chole Bhature",
      price: 13.99,
      category: "Main Course",
      description: "Chickpea curry with fried bread",
      image: "https://example.com/chole-bhature.jpg",
      spiceLevel: "Medium",
      vegetarian: true,
    },
    {
      id: "item_001_018",
      name: "Masala Chai",
      price: 3.99,
      category: "Beverage",
      description: "Spiced Indian tea",
      image: "https://example.com/masala-chai.jpg",
      spiceLevel: "None",
      vegetarian: true,
    },
    {
      id: "item_001_019",
      name: "Lamb Rogan Josh",
      price: 21.99,
      category: "Main Course",
      description: "Kashmiri lamb curry",
      image: "https://example.com/rogan-josh.jpg",
      spiceLevel: "Medium",
      vegetarian: false,
    },
    {
      id: "item_001_020",
      name: "Gulab Jamun",
      price: 6.99,
      category: "Dessert",
      description: "Sweet milk dumplings in syrup",
      image: "https://example.com/gulab-jamun.jpg",
      spiceLevel: "None",
      vegetarian: true,
    },
  ]
};

export default menuItems;
